name: 'Publish Google Play'
description: 'Publish Google Play GitHub action'
inputs:
  aab-path:
    description: >
      Specify the path of the Android App Bundle file to upload.
    required: true
  package-name:
    description: >
      Specify the name of the package to be uploaded.
    required: true
  release-name:
    description: >
      Specify the name of the release.
    required: false
  release-note:
    description: >
      Specify the release note for the uploaded package.

      see: https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks#localizedtext
    required: false
  service-account-key:
    description: >
      Specify the service account key.
    required: true
  status:
    description: >
      Specify the status of the uploaded package.
      Valid values are: completed, draft, halted, inProgress, and statusUnspecified.

      see: https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks#Status
    required: false
    default: completed
  track:
    description: >
      Specifies the track to be uploaded.
      Valid values are: alpha, beta, production, and internal.
    required: false
    default: internal
runs:
  using: node20
  main: dist/index.js
branding:
  icon: upload-cloud
  color: orange